# Generated by Django 4.0.6 on 2023-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('USER', 'user'), ('SUPPLIER', 'supplier')], max_length=20),
        ),
    ]
