# Generated by Django 4.2.3 on 2023-07-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "admin"),
                    ("USER", "user"),
                    ("SUPPLIER", "supplier"),
                ],
                max_length=30,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "admin"),
                    ("USER", "user"),
                    ("SUPPLIER", "supplier"),
                ],
                max_length=20,
            ),
        ),
    ]
